version: '3.8'
name: micro-benchmark
services:
  nodejs-standard:
    hostname: nodejs-standard
    build:
      context: ./nodejs
      dockerfile: nodejs.dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
    ports:
      - "5300-5309:8080"
    environment:
      DB_HOST: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "world"
    networks:
      - telemetry
    restart: always

networks:
  telemetry:
    external: true