version: '3.8'
name: micro-benchmark
services:
  nodejs-elastic:
    hostname: nodejs-elastic
    build:
      context: ./nodejs
      dockerfile: nodejs.dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
    ports:
      - "5300-5309:8080"
    environment:
      DB_HOST: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "world"
      NODE_OPTIONS: "-r elastic-apm-node/start.js"
      ELASTIC_APM_ENABLED: True
      ELASTIC_APM_SERVICE_NAME: nodejs-elastic
      ELASTIC_APM_SERVER_URL: http://apm-server:8200
      ELASTIC_APM_TRANSACTION_SAMPLE_RATE: 1.0
    networks:
      - telemetry
    restart: always

networks:
  telemetry:
    external: true