receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    # Change to 'http://jaeger:4317' to send to Jaeger
    endpoint: "http://apm-server:8200"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
