replicaCount: 1
elasticsearchHosts: "http://elasticsearch-master:9200"
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  type: NodePort
  port: 5601
  nodePort: 32000