version: '3.8'
name: micro-benchmark
services:
  java-otel:
    hostname: java-otel
    build:
      context: ./spring
      dockerfile: spring-jpa.dockerfile
      args:
        OPENTELEMETRY: true
    deploy:
      resources:
        limits:
          cpus: '1'
    ports:
      - "5210-5219:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/spring/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: "java-otel"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_LOGS_EXPORTER: "none"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
    networks:
      - telemetry
    restart: always

networks:
  telemetry:
    external: true
