version: '3.8'
name: experiment
services:
  experiment:
    build:
      context: ..
      dockerfile: Dockerfile-request-based
    deploy:
      resources:
        limits:
          cpus: '1'
    environment:
      OTLP_ENDPOINT: "http://otel-collector:4317"
      EXPERIMENT_ENDPOINT: "db"
      EXPERIMENT_ITERATIONS: 100000
    networks:
      - telemetry
    volumes:
      - ./output:/app/output

networks:
  telemetry:
    external: true
