version: '3.8'
name: micro-benchmark
services:
  java-spring-standard:
    hostname: java-spring-standard
    build:
      context: ./spring
      dockerfile: spring-jpa.dockerfile
    ports:
      - "5200-5209:8080"
    networks:
      - telemetry

networks:
  telemetry:
    external: true