version: '3.8'
name: micro-benchmark-python-otel
services:
  flask:
    build:
      context: ./python
      dockerfile: Dockerfile
      args:
        - REQUIREMENTS_FILE=requirements-otel.txt
        - OPENTELEMETRY=true
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=postgres
      - FLASK_RUN_PORT=5000
      - FLASK_RUN_HOST=0.0.0.0
      - OTEL_SERVICE_NAME=python-otel
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
    networks:
      - telemetry

networks:
  telemetry:
    external: true
