version: '3.8'
name: micro-benchmark
services:
  python-flask-standard:
    hostname: python-flask-standard
    build:
      context: ./flask
      dockerfile: Dockerfile
#    deploy:
#      replicas: 3
    ports:
      - "5000-5009:8080"
    environment:
      - DB_HOST=postgres
      - FLASK_RUN_PORT=8080
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - telemetry

networks:
  telemetry:
    external: true