version: '3.8'
name: micro-benchmark-python
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - FLASK_RUN_PORT=5000
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - telemetry

networks:
  telemetry:
    external: true