version: '3.8'
name: micro-benchmark
services:
  python-standard:
    hostname: python-standard
    build:
      context: ./flask
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
    ports:
      - "5000-5009:8080"
    environment:
      - DB_HOST=postgres
      - FLASK_RUN_PORT=8080
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - telemetry
    restart: always

networks:
  telemetry:
    external: true