version: '3.8'
name: micro-benchmark
services:
  python-otel:
    hostname: python-otel
    build:
      context: ./flask
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: requirements-otel.txt
        OPENTELEMETRY: true
    deploy:
      resources:
        limits:
          cpus: '1'
    ports:
      - "5020-5029:8080"
    environment:
      - DB_HOST=postgres
      - FLASK_RUN_PORT=8080
      - FLASK_RUN_HOST=0.0.0.0
#      - OPENTELEMETRY_ENABLED=True
      - OTEL_SERVICE_NAME=python-otel
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
    networks:
      - telemetry
    restart: always

networks:
  telemetry:
    external: true
