version: '3.8'
name: postgres
services:
  db:
    hostname: postgres
    build:
      context: ../postgres
      dockerfile: ../postgres/Dockerfile
    ports:
      - "10000-10100:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - telemetry

volumes:
  postgres_data:

networks:
  telemetry:
    external: true