version: '3.8'
name: micro-benchmark
services:
  calibrator:
    build: .
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LANGUAGE: "java"
    networks:
      - telemetry
    restart: always

networks:
  telemetry:
    external: true