version: '3.8'
name: micro-benchmark
services:
  tests:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
    build: .
    volumes:
      - ./results:/app/results
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - telemetry

networks:
  telemetry:
    external: true