version: '3.8'
name: micro-benchmark
services:
  go-standard:
    hostname: go-standard
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
    ports:
      - "5100-5109:8080"
    environment:
      - DB_HOST=postgres
      - APP_PORT=8080
    networks:
      - telemetry
    restart: always

networks:
  telemetry:
    external: true