version: '3.8'
name: micro-benchmark
services:
  go-otel:
    hostname: go-otel
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_FILE_NAME: server-otel
    deploy:
      resources:
        limits:
          cpus: '1'
    ports:
      - "5110-5119:8080"
    environment:
      - DB_HOST=postgres
      - APP_PORT=8080
    volumes:
      - otel:/app
    networks:
      - telemetry
    restart: always

  go-auto:
    image: otel/autoinstrumentation-go:v0.12.0-alpha
    privileged: true
    pid: "host"
    environment:
      - OTEL_GO_AUTO_TARGET_EXE=/app/server-otel
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_GO_AUTO_INCLUDE_DB_STATEMENT=true
      - OTEL_SERVICE_NAME=go-otel
      - OTEL_PROPAGATORS=tracecontext
    volumes:
      - otel:/app
      - /proc:/host/proc
    depends_on:
      - go-otel
    networks:
      - telemetry

volumes:
  otel:

networks:
  telemetry:
    external: true
