version: '3.8'
name: micro-benchmark-go
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    environment:
      - DB_HOST=postgres
      - APP_PORT=5100
    volumes:
      - go-server:/root
    networks:
      - telemetry

volumes:
  go-server:

networks:
  telemetry:
    external: true