version: '3.8'
name: micro-benchmark-go
services:
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    depends_on:
      - db
    environment:
      - DB_HOST=postgres
      - APP_PORT=5100
    networks:
      - telemetry

networks:
  telemetry:
    external: true