[framework]
name = "nodejs"

[postgres]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "nodejs"
webserver = "None"
versus = "nodejs"
dockerfile = "nodejs.dockerfile"